# Generated by Django 3.2.3 on 2021-05-15 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_task.contract'),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='test_task.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='test_task.manufacturer'),
        ),
    ]
